#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

# ╔╦╗┌─┐┌┐┌┬┌┬┐┌─┐┬─┐   ┬   ╔╦╗┬┌─┐┌─┐┬  ┌─┐┬ ┬
# ║║║│ │││││ │ │ │├┬┘  ┌┼─   ║║│└─┐├─┘│  ├─┤└┬┘
# ╩ ╩└─┘┘└┘┴ ┴ └─┘┴└─  └┘   ═╩╝┴└─┘┴  ┴─┘┴ ┴ ┴

# See https://wiki.hyprland.org/Configuring/Monitors/

# monitor=,preferred,auto,auto

# RogueOne
# eDP-1 Lenovo Laptop screen
# DP-2 - Dell Monitor 5k2k via DisplayLink

# Laptop Monitor
monitor=eDP-1,1920x1080@60.02,0x0,1.0


# External Dell Monitor
monitor=HDMI-A-1,3440x1440@59.97,1920,1.0

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄
