#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄

# ╔╦╗┌─┐┌┐┌┬┌┬┐┌─┐┬─┐   ┬   ╔╦╗┬┌─┐┌─┐┬  ┌─┐┬ ┬
# ║║║│ │││││ │ │ │├┬┘  ┌┼─   ║║│└─┐├─┘│  ├─┤└┬┘
# ╩ ╩└─┘┘└┘┴ ┴ └─┘┴└─  └┘   ═╩╝┴└─┘┴  ┴─┘┴ ┴ ┴

# See https://wiki.hyprland.org/Configuring/Monitors/

# Laptop Monitor
monitor= eDP-1, 1920x1080@60.02000, 0x0, 1.00


# External Dell Monitor

#!▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄ ▄▄
